---
title: "Example survival plots"
description: |
  Looking at different options to produce survival (time to event) plot including survminer, ggfortify and broom.
author:
  - name: Mark Baillie 
    url: https://bailliem.github.io/visR-gists/
    affiliation: visR
    affiliation_url: https://github.com/openpharma/visR
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE, results=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

library(rmarkdown)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(here)
library(patchwork)
library(survminer)
library(ggfortify)
library(survival)
library(broom)

#theme_set(theme_minimal(base_size = 8))
theme_set(theme_linedraw(base_size = 8))

```


# Purpose

To explore different options to produce a survival plot. 

# Example 

A typical example survival model with a binary stratum. 

```{r}
fit <- survfit(Surv(time, status) ~ sex, data = lung)
fit
```


# Survminer

Plot survival curves by strata using survminer. 

```{r}
ggsurvplot(fit, data = lung)
```


```{r}
ggsurvplot(
   fit,                     # survfit object with calculated statistics.
   data = lung,  # data used to fit survival curves. 
   risk.table = TRUE,         # show risk table.
   pval = TRUE,               # show p-value of log-rank test.
   conf.int = TRUE,           # show confidence intervals for 
                              # point estimaes of survival curves.
   xlim = c(0,1000),          # present narrower X axis, but not affect
                              # survival estimates.
   break.time.by = 500,       # break X axis in time intervals by 500.
   ggtheme = theme_minimal(), # customize plot and risk table with a theme.
   risk.table.y.text.col = T, # colour risk table text annotations.
   risk.table.y.text = FALSE # show bars instead of names in text annotations
                             # in legend of risk table
)
```



## GGfortify


```{r}
autoplot(fit)
```

## Broom 

First tidy the survival object. 

```{r}
td <- tidy(fit)
td %>% glimpse()
```

Then plot with ggplot. 

```{r}
surv_plot <- td %>% 
  ggplot(aes(time, estimate, group = strata)) + 
  geom_line() +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .2)

surv_plot
```


Plot risk table 

```{r}
surv_tab <-
  td %>% 
  mutate(
    row = if_else(strata == "sex=1", 1, 0)  
  ) %>%
  ggplot(aes(x = time, y = row , label = n.risk)) + 
  geom_text() 

surv_tab
```

```{r}
surv_plot / surv_tab
```

How to recreate the risk table in surv_miner. 
```{r}
td %>% 
  group_by()
  
  
  mutate(
    row = if_else(strata == "sex=1", 1, 0)  
  ) %>%
  ggplot(aes(x = time, y = row , label = n.risk)) + 
  geom_text() 


tmp %>%
group_by(id) %>%
slice(c(1, n())) %>%
ungroup()
```


# Further reading

https://socviz.co/modeling.html
