

---
title: "Forest plot"
date: "`r Sys.Date()`"
output:
    bookdown::html_document2:
        toc: true
        toc_float:
            collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


```{r setupR, results=FALSE, warning=FALSE}
library(rmarkdown)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(here)
library(patchwork)
library(survminer)
library(ggfortify)
library(glmnet)
library(broom)
library(broom.mixed)

theme_set(theme_minimal(base_size = 8))
#theme_set(theme_linedraw(base_size = 8))
```


# Purpose

Broom.mixed and ggplot

See https://cran.r-project.org/web/packages/broom.mixed/index.html
See https://socviz.co/modeling.html
https://cran.r-project.org/web/packages/dotwhisker/vignettes/dotwhisker-vignette.html

https://cran.r-project.org/web/packages/broom.mixed/vignettes/broom_mixed_intro.html

```{r}
library("dplyr")
library("tidyr")
library("broom.mixed")
if (require("brms") && require("dotwhisker") && require("ggplot2")) {
    L <- load(system.file("extdata", "brms_example.rda", package="broom.mixed"))
    gg0 <- (tidy(brms_crossedRE)
        ## disambiguate
        %>% mutate(term=ifelse(grepl("sd__(Int",term,fixed=TRUE),
                               paste(group,term,sep="."),
                               term))
        %>% dwplot
    )
    gg0 + geom_vline(xintercept=0,lty=2)
}
```

