---
title: "Forest plot"
date: "`r Sys.Date()`"
output:
    bookdown::html_document2:
        toc: true
        toc_float:
            collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


```{r setupR, results=FALSE, warning=FALSE}
library(rmarkdown)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(here)
library(patchwork)
library(survminer)
library(ggfortify)
library(glmnet)
library(broom)

theme_set(theme_minimal(base_size = 8))
#theme_set(theme_linedraw(base_size = 8))
```

```{r}
fit <- lm(mpg ~ wt + qsec, mtcars)
```


```{r}
td <- tidy(fit, conf.int = TRUE)
head(td)
```


```{r}
ggplot(td, aes(estimate, term, color = term)) +
    geom_point() +
    geom_errorbarh(aes(xmin = conf.low, xmax = conf.high)) +
    geom_vline(xintercept = 0)
```

## Marginal effect models
Using broom and ggplot. 

```{r}
## Context: https://twitter.com/grant_mcdermott/status/1210654424600731648

library(tidyverse)
library(broom)
library(hrbrthemes) ## theme(s) I like

df = 
  mtcars %>%
  mutate(vs = factor(vs), am = factor(am))

fit1 = lm(mpg ~ vs * am * wt, data = df) 
fit1_coefs = tidy(fit1, conf.int = T) 

fit2 = lm(mpg ~ vs / am / wt, data = df)
fit2_coefs = tidy(fit2, conf.int = T) 

## Option 1: Facet by model
bind_rows(
  fit1_coefs %>% mutate(model = "Partial MEs"),
  fit2_coefs %>% mutate(model = "Full MEs")
) %>%
  filter(grepl("wt", term)) %>%
  ## Optional regexp work to make plot look nicier  
  mutate(
    am = ifelse(grepl("am1", term), "Automatic", "Manual"),
    vs = ifelse(grepl("vs1", term), "V-shaped", "Straight"),
    x_lab = paste(am, vs, sep="\n")
  ) %>%
  ggplot(aes(x=x_lab, y=estimate, ymin=conf.low, ymax=conf.high)) +
  geom_pointrange() +
  geom_hline(yintercept = 0, col = "orange") +
  labs(
    x = NULL, y = "Marginal effect (Δ in MPG : Δ in '000 lbs)",
    title = " Marginal effect of vehicle weight on MPG", 
    subtitle = "Conditional on transmission type and engine shape"
  ) +
  facet_wrap(~ model) +
  theme_ipsum() 

## Option 2: Share plot area, but use position dodge and colouring
bind_rows(
  fit1_coefs %>% mutate(model = "Partial MEs"),
  fit2_coefs %>% mutate(model = "Full MEs")
) %>%
  filter(grepl("wt", term)) %>%
  ## Optional regexp work to make plot look nicier  
  mutate(
    am = ifelse(grepl("am1", term), "Automatic", "Manual"),
    vs = ifelse(grepl("vs1", term), "V-shaped", "Straight"),
    x_lab = paste(am, vs, sep="\n")
  ) %>%
  ggplot(aes(x=x_lab, y=estimate, ymin=conf.low, ymax=conf.high)) +
  geom_pointrange(aes(col = model), position = position_dodge(width = 0.5)) +
  geom_hline(yintercept = 0, col = "black") +
  labs(
    x = NULL, y = "Marginal effect (Δ in MPG : Δ in '000 lbs)",
    title = " Marginal effect of vehicle weight on MPG", 
    subtitle = "Conditional on transmission type and engine shape"
  ) +
  theme_ipsum() 
```


