---
title: "Forest plot"
date: "`r Sys.Date()`"
output:
    bookdown::html_document2:
        toc: true
        toc_float:
            collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```


```{r setupR, results=FALSE, warning=FALSE}
library(rmarkdown)
library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(here)
library(patchwork)
library(survminer)
library(ggfortify)
library(glmnet)
library(broom)

theme_set(theme_minimal(base_size = 8))
#theme_set(theme_linedraw(base_size = 8))
```


# Purpose



```{r}
set.seed(03-19-2015)

# generate data with 5 real variables and 45 null, on 100 observations
x <- matrix(rnorm(100 * 50), 100)
beta <- c(rnorm(5, 0, 1), rep(0, 50 - 5))
y <- c(t(beta) %*% t(x)) + rnorm(50, sd = 3)

glmnet_fit <- cv.glmnet(x,y)
```

```{r}
tidied_cv <- tidy(glmnet_fit)
glance_cv <- glance(glmnet_fit)

head(tidied_cv)
```



```{r}
head(glance_cv)
```

```{r}
library(ggplot2)

ggplot(tidied_cv, aes(lambda, estimate)) + geom_line(color = "red") +
    geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .2) +
    scale_x_log10() +
    geom_vline(xintercept = glance_cv$lambda.min) +
    geom_vline(xintercept = glance_cv$lambda.1se, lty = 2)
```

